# Default values for webui

image:
  registry: ghcr.io
  repository: borjis131/webui
  tag: "v2.7.5"
  pullPolicy: IfNotPresent

services:
  webui:
    type: NodePort
    nodePort: 30999

global:
  containerPorts:
    webui: 9999
