version: "2.4"

services:
  db:
    container_name: db
    image: "mongo:${MONGODB_VERSION}"
    command: "mongod --bind_ip 0.0.0.0 --port 27017"
    networks:
      open5gs:
        aliases:
          - db.open5gs.org
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb
    ports:
      - "0.0.0.0:27017:27017/tcp"

  nrf:
    container_name: nrf
    image: "nrf:${OPEN5GS_VERSION}"
    build:
      context: ../../images/nrf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: "-c /open5gs/config/nrf.yaml"
    networks:
      open5gs:
        aliases:
          - nrf.open5gs.org
    volumes:
      - ../../configs/scp-model-d/nrf.yaml:/open5gs/config/nrf.yaml

  scp:
    container_name: scp
    image: "scp:${OPEN5GS_VERSION}"
    build:
      context: ../../images/scp
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: "-c /open5gs/config/scp.yaml"
    networks:
      open5gs:
        aliases:
          - scp.open5gs.org
    volumes:
      - ../../configs/scp-model-d/scp.yaml:/open5gs/config/scp.yaml

  ausf:
    container_name: ausf
    image: "ausf:${OPEN5GS_VERSION}"
    build:
      context: ../../images/ausf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: "-c /open5gs/config/ausf.yaml"
    networks:
      open5gs:
        aliases:
          - ausf.open5gs.org
    volumes:
      - ../../configs/scp-model-d/ausf.yaml:/open5gs/config/ausf.yaml
    depends_on:
      - nrf
      - scp

  udm:
    container_name: udm
    image: "udm:${OPEN5GS_VERSION}"
    build:
      context: ../../images/udm
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: "-c /open5gs/config/udm.yaml"
    networks:
      open5gs:
        aliases:
          - udm.open5gs.org
    volumes:
      - ../../configs/scp-model-d/udm.yaml:/open5gs/config/udm.yaml
    depends_on:
      - nrf
      - scp

  udr:
    container_name: udr
    image: "udr:${OPEN5GS_VERSION}"
    build:
      context: ../../images/udr
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: "-c /open5gs/config/udr.yaml"
    networks:
      open5gs:
        aliases:
          - udr.open5gs.org
    volumes:
      - ../../configs/scp-model-d/udr.yaml:/open5gs/config/udr.yaml
    depends_on:
      - db
      - nrf
      - scp

  nssf:
    container_name: nssf
    image: "nssf:${OPEN5GS_VERSION}"
    build:
      context: ../../images/nssf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: "-c /open5gs/config/nssf.yaml"
    networks:
      open5gs:
        aliases:
          - nssf.open5gs.org
    volumes:
      - ../../configs/scp-model-d/nssf.yaml:/open5gs/config/nssf.yaml
    depends_on:
      - nrf
      - scp

  bsf:
    container_name: bsf
    image: "bsf:${OPEN5GS_VERSION}"
    build:
      context: ../../images/bsf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: "-c /open5gs/config/bsf.yaml"
    networks:
      open5gs:
        aliases:
          - bsf.open5gs.org
    volumes:
      - ../../configs/scp-model-d/bsf.yaml:/open5gs/config/bsf.yaml
    depends_on:
      - nrf
      - scp

  pcf:
    container_name: pcf
    image: "pcf:${OPEN5GS_VERSION}"
    build:
      context: ../../images/pcf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: "-c /open5gs/config/pcf.yaml"
    networks:
      open5gs:
        aliases:
          - pcf.open5gs.org
    volumes:
      - ../../configs/scp-model-d/pcf.yaml:/open5gs/config/pcf.yaml
    depends_on:
      - db
      - nrf
      - scp

  amf:
    container_name: amf
    image: "amf:${OPEN5GS_VERSION}"
    build:
      context: ../../images/amf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: "-c /open5gs/config/amf.yaml"
    networks:
      open5gs:
        aliases:
          - amf.open5gs.org
    volumes:
      - ../../configs/scp-model-d/amf.yaml:/open5gs/config/amf.yaml
    depends_on:
      - nrf
      - scp
    ports:
      - "0.0.0.0:38412:38412/sctp"

  smf:
    container_name: smf
    image: "smf:${OPEN5GS_VERSION}"
    build:
      context: ../../images/smf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: "-c /open5gs/config/smf.yaml"
    networks:
      open5gs:
        aliases:
          - smf.open5gs.org
    volumes:
      - ../../configs/scp-model-d/smf.yaml:/open5gs/config/smf.yaml
    depends_on:
      - nrf
      - scp
      - upf

  upf:
    container_name: upf
    image: "upf:${OPEN5GS_VERSION}"
    build:
      context: ../../images/upf
      args:
        - OPEN5GS_VERSION=${OPEN5GS_VERSION}
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    command: "-c /open5gs/config/upf.yaml"
    networks:
      open5gs:
        aliases:
          - upf.open5gs.org
    extra_hosts:
      docker-host.external-ip: ${DOCKER_HOST_IP}
    volumes:
      - ../../configs/scp-model-d/upf.yaml:/open5gs/config/upf.yaml
    ports:
      - "0.0.0.0:2152:2152/udp"
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1

networks:
  open5gs:
    name: open5gs
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-ogs
    ipam:
      config:
        - subnet: 10.33.33.0/24
          gateway: 10.33.33.1

volumes:
  db_data:
    name: open5gs_db_data
    labels:
      org.open5gs.mongodb_version: ${MONGODB_VERSION}
  db_config:
    name: open5gs_db_config
    labels:
      org.open5gs.mongodb_version: ${MONGODB_VERSION}