db_uri: mongodb://db.open5gs.org/open5gs

logger:
  file: /open5gs/install/var/log/open5gs/udr.log

global:
  max:
    ue: 1024

udr:
  sbi:
    server:
      - address: udr.5gc.mnc001.mcc001.3gppnetwork.org
        port: 80
    client:
      nrf:
        - uri: http://nrf.5gc.mnc001.mcc001.3gppnetwork.org:80
