logger:
  file:
    path: /var/log/open5gs/udm.log

global:

udm:
  sbi:
    server:
      - address: udm.5gc.mnc001.mcc001.3gppnetwork.org
        port: 80
    client:
      nrf:
        - uri: http://nrf.5gc.mnc001.mcc001.3gppnetwork.org:80
