logger:
  file: /open5gs/install/var/log/open5gs/upf.log

global:
  max:
    ue: 1024

upf:
  pfcp:
    server:
      - address: upf.open5gs.org
    client:
  gtpu:
    server:
      - address: upf.open5gs.org
  session:
    - subnet: 10.45.0.1/16
