apiVersion: v2

name: ausf
description: Open5GS AUSF Helm chart
version: 0.3.4
type: application
appVersion: "v2.7.5"

icon: https://open5gs.org/assets/img/open5gs-logo.png

dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
