logger:
  file: /open5gs/install/var/log/open5gs/ausf.log

logger:
  file: /open5gs/install/var/log/open5gs/ausf.log

global:
  max:
    ue: 1024

ausf:
  sbi:
    server:
      - address: ausf.open5gs.org
        port: 80
    client:
      nrf:
        - uri: http://nrf.open5gs.org:80
