# Default values for open5gs

#nf:
  #enabled: true/false
  #image:
  #config: {}
  #global:
    #containerPorts:

#db:
  #enabled: true/false
  #image:
  #services:
    #db:
      #type: NodePort/ClusterIP
      #nodePort:
  #config: {}
  #storage:
    #volumeClaimTemplate:
      #spec:
        #storageClassName: ""
        #resources:
          #requests:
            #storage: 1Gi
        #accessModes:
          #- ReadWriteOnce
  #global:
    #containerPorts:

#webui:
  #enabled: true/false
  #image:
  #services:
    #webui:
      #type: NodePort/ClusterIP
      #nodePort:
  #global:
    #containerPorts:

#nssf:
  #enabled: true/false
  #image:
  #config: {}
  #global:
    #containerPorts:
    #mobileNetwork:
      #plmn:
        #s_nssai:

#amf:
  #enabled: true/false
  #image:
  #services:
    #ngap:
      #type: LoadBalancer/ClusterIP
      #loadBalancerIP:
      #provider:
  #config: {}
  #global:
    #containerPorts:
    #mobileNetwork:
      #name:
      #plmn:

#smf:
  #enabled: true/false
  #image:
  #config: {}
  #global:
    #containerPorts:
    #mobileNetwork:
      #dataNetwork:

#upf:
  #enabled: true/false
  #image:
  #services:
    #gtpu:
      #type: LoadBalancer/ClusterIP
      #loadBalancerIP:
      #provider:
  #config: {}
  #global:
    #mobileNetwork:
      #dataNetwork:

global:
  networkFunctions:
    upf: []
  containerPorts:
    db: 27017
    sbi: 80
    webui: 9999
  mobileNetwork:
    name: Open5GS
    plmn:
      mcc: "001"
      mnc: "01"
      tac: 1
      s_nssai:
        - sst: 1
          sd: "000001"
    dataNetwork:
      subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dnn: internet

db:
  enabled: true
  services:
    db:
      type: NodePort
      nodePort: 30007

webui:
  enabled: true
  services:
    webui:
      type: NodePort
      nodePort: 30999

nrf:
  enabled: true

ausf:
  enabled: true

bsf:
  enabled: true

nssf:
  enabled: true

pcf:
  enabled: true

udm:
  enabled: true

udr:
  enabled: true

amf:
  enabled: true
  services:
    ngap:
      type: LoadBalancer
      loadBalancerIP: 10.33.0.2
      provider: MetalLB

smf:
  enabled: true

upf:
  enabled: true
  services:
    gtpu:
      type: LoadBalancer
      loadBalancerIP: 10.33.0.3
      provider: MetalLB
